version: "3.9"

services:
  em-sgx-1:
    image: gianlu33/reactive-event-manager:latest
    expose:
      - "5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  em-sgx-2:
    image: gianlu33/reactive-event-manager:latest
    expose:
      - "6000-6010"
    environment:
      - EM_PORT=6000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  aesm-client:
    image: gianlu33/aesm-client:latest
    expose:
      - "13741"
    environment:
      - AESM_PORT=13741
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  manager:
    image: gianlu33/attestation-manager:native
    expose:
      - "1234"
  deployer:
    image: gianlu33/reactive-tools:latest
    command: ./deployer.sh
    depends_on:
      - em-sgx-1
      - em-sgx-2
      - aesm-client
      - manager
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
