version: "3.9"

services:
  node-sgx:
    image: authexec/event-manager-sgx:latest
    ports:
      - "5000-5010:5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
      - EM_MEASURE_TIME=true
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
    devices:
      - "/dev/isgx:/dev/isgx"
  node-trustzone:
    image: authexec/event-manager-trustzone:latest
    ports:
      - "6000:1236"
    environment:
      - PORT=6000
      - IMX=1
    volumes:
      - "/opt/optee:/opt/optee"
    devices:
      - "/dev/ttyUSB1:/dev/NW"
      - "/dev/ttyUSB0:/dev/SW"
  aesm-client:
    image: authexec/aesm-client:latest
    expose:
      - "13741"
    environment:
      - AESM_PORT=13741
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  admin:
    image: authexec/reactive-tools:latest
    command: ./deploy.sh
    depends_on:
      - node-sgx
      - node-trustzone
      - aesm-client
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
