version: "3.9"

services:
  node-sgx:
    image: authexec/event-manager-sgx:latest
    expose:
      - "5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
      - EM_MEASURE_TIME=false
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  node-sancus:
    image: authexec/event-manager-sancus:latest
    expose:
      - "6000"
    environment:
      - ELF=reactive.elf
      - PORT=6000
    devices:
      - "/dev/ttyUSB2:/dev/RIOT"
      - "/dev/ttyUSB3:/dev/UART"
  aesm-client:
    image: authexec/aesm-client:latest
    expose:
      - "13741"
    environment:
      - AESM_PORT=13741
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  admin:
    image: authexec/reactive-tools:latest
    command: ./deploy.sh
    depends_on:
      - node-sgx
      - node-sancus
      - aesm-client
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
