version: "3.9"

services:
  node-sgx:
    image: authexec/event-manager-sgx:latest
    ports:
      - "5000-5010:5000-5010"
      - "48879:48879"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
      - EM_MEASURE_TIME=true
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  node-sancus-1:
    image: authexec/event-manager-sancus:latest
    ports:
      - "6000:6000"
    environment:
      - ELF=reactive.elf
      - PORT=6000
    devices:
      - "/dev/ttyUSB4:/dev/RIOT"
      - "/dev/ttyUSB5:/dev/UART"
  node-sancus-2:
    image: authexec/event-manager-sancus:latest
    ports:
      - "7000:7000"
    environment:
      - ELF=reactive_led.elf
      - PORT=7000
    devices:
      - "/dev/ttyUSB2:/dev/RIOT"
      - "/dev/ttyUSB3:/dev/UART"
  node-sancus-3:
    image: authexec/event-manager-sancus:latest
    ports:
      - "8000:8000"
    environment:
      - ELF=reactive_led.elf
      - PORT=8000
    devices:
      - "/dev/ttyUSB6:/dev/RIOT"
      - "/dev/ttyUSB7:/dev/UART"
  node-trustzone:
    image: authexec/event-manager-trustzone:latest
    ports:
      - "9000:1236"
    environment:
      - PORT=9000
      - IMX=1
    volumes:
      - "/opt/optee:/opt/optee"
    devices:
      - "/dev/ttyUSB1:/dev/NW"
      - "/dev/ttyUSB0:/dev/SW"
  aesm-client:
    image: authexec/aesm-client:latest
    expose:
      - "13741"
    environment:
      - AESM_PORT=13741
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  admin:
    image: authexec/reactive-tools:latest
    command: ./deploy.sh ${AUTO}
    depends_on:
      - node-sgx
      - node-sancus-1
      - node-sancus-2
      - node-sancus-3
      - node-trustzone
      - aesm-client
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
