version: "3.9"

services:
  node-sancus-1:
    image: authexec/event-manager-sancus:latest
    expose:
      - "6000"
    environment:
      - ELF=reactive.elf
      - PORT=6000
    devices:
      - "/dev/ttyUSB1:/dev/RIOT"
      - "/dev/ttyUSB0:/dev/UART"
  node-sancus-2:
    image: authexec/event-manager-sancus:latest
    expose:
      - "6000"
    environment:
      - ELF=reactive_led.elf
      - PORT=6000
    devices:
      - "/dev/ttyUSB2:/dev/RIOT"
      - "/dev/ttyUSB3:/dev/UART"
  node-sancus-3:
    image: authexec/event-manager-sgx:latest
    expose:
      - "5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  node-sgx:
    image: authexec/event-manager-sgx:latest
    expose:
      - "5000-5010"
    ports:
      - "48879:48879"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=true
    devices:
      - "/dev/isgx:/dev/isgx"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  node-trustzone:
    image: authexec/event-manager-trustzone:latest
    expose:
      - "1236"
    environment:
      - PORT=1236
    volumes:
      - "/opt/optee:/opt/optee"
  aesm-client:
    image: authexec/aesm-client:latest
    expose:
      - "13741"
    environment:
      - AESM_PORT=13741
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
  admin:
    image: authexec/reactive-tools:latest
    command: ./deploy.sh
    depends_on:
      - node-sancus-1
      - node-sancus-2
      - node-sancus-3
      - node-sgx
      - node-trustzone
      - aesm-client
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
