version: "3.9"

services:
  node-sgx:
    image: authexec/event-manager-sgx:latest
    ports:
      - "5000-5010:5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=false
      - EM_MEASURE_TIME=true
  node-trustzone:
    image: authexec/event-manager-trustzone:latest
    ports:
      - "1236:1236"
    environment:
      - PORT=1236
    volumes:
      - "/opt/optee:/opt/optee"
  admin:
    image: authexec/reactive-tools:latest
    command: ./deploy.sh
    depends_on:
      - node-sgx
      - node-trustzone
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
