version: "3.9"

services:
  node-native-1:
    image: authexec/event-manager-sgx:latest
    expose:
      - "5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=false
      - EM_MEASURE_TIME=true
  node-native-2:
    image: authexec/event-manager-sgx:latest
    expose:
      - "5000-5010"
    environment:
      - EM_PORT=5000
      - EM_LOG=info
      - EM_THREADS=16
      - EM_PERIODIC_TASKS=false
      - EM_SGX=false
      - EM_MEASURE_TIME=true
  admin:
    image: authexec/reactive-tools:latest
    command: ./deploy.sh
    depends_on:
      - node-native-1
      - node-native-2
    volumes:
      - ".:/usr/src/app"
      - "/usr/local/cargo/git:/usr/local/cargo/git" # for caching builds
      - "/usr/local/cargo/registry:/usr/local/cargo/registry" # same
